# Generated by Django 6.0.4 on 2026-04-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.JSONField(blank=True, default=list)),
                ('highest_score', models.FloatField(default=0.0)),
                ('flag_level', models.CharField(choices=[('STRONG', 'Strong Warning'), ('MEDIUM', 'Suggestion'), ('NONE', 'No Warning')], default='NONE', max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('override_reason', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_report', to='projects.submission')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
