# Generated by Django 6.0.4 on 2026-04-25 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHASE_COMPLETE', 'Phase Completed'), ('NEW_SUBMISSION', 'New Submission'), ('DEADLINE', 'Deadline Alert'), ('FEEDBACK', 'New Feedback'), ('PHASE_UNLOCK', 'Phase Unlocked'), ('SIMILARITY_WARNING', 'Similarity Warning')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx')],
            },
        ),
    ]
