# Generated by Django 6.0.4 on 2026-04-25 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Domain name (e.g., 'Artificial Intelligence', 'Data Science')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SYNOPSIS', 'Synopsis'), ('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2'), ('FINAL_REPORT', 'Final Report'), ('PUBLICATION', 'Publication')], help_text='Phase identifier', max_length=50, unique=True)),
                ('order', models.IntegerField(help_text='Sequential order (1, 2, 3, 4, 5)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Phase description and requirements')),
                ('deadline_offset_days', models.IntegerField(default=30, help_text='Days from project creation for this phase deadline')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='projects_ph_order_6dc809_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title (must be unique across all projects)', max_length=500, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Current project status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='Project domain/category', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.domain')),
                ('guide', models.ForeignKey(blank=True, help_text='Assigned guide/teacher for this project', limit_choices_to={'role': 'GUIDE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_guided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current submission status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.ForeignKey(help_text='Phase this submission is for', on_delete=django.db.models.deletion.CASCADE, to='projects.phase')),
                ('project', models.ForeignKey(help_text='Project this submission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Feedback comment from guide')),
                ('resolved', models.BooleanField(default=False, help_text='Has this feedback been resolved by the team?')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the feedback was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(help_text='Guide who provided this feedback', limit_choices_to={'role__in': ['GUIDE', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_resolved', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='Submission this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Team Leader'), ('MEMBER', 'Team Member')], default='MEMBER', help_text='Role within the team', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
                ('user', models.ForeignKey(help_text='Student team member', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Auto-incrementing version number per submission')),
                ('file', models.FileField(help_text='Submission file (pdf, doc, docx, txt, zip, rar, py, ipynb, jpg, jpeg, png)', upload_to='submissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip', 'rar', 'py', 'ipynb', 'jpg', 'jpeg', 'png'])])),
                ('change_summary', models.TextField(blank=True, help_text='What changed in this version?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='File metadata (size, type, etc.)')),
                ('submission', models.ForeignKey(help_text='Submission this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.submission')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submission', 'version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['name'], name='projects_do_name_873729_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['guide', 'status'], name='projects_pr_guide_i_838a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['domain'], name='projects_pr_domain__87f187_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='projects_pr_title_ba614c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', 'phase', 'status'], name='projects_su_project_bf5b76_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='projects_su_status_a9dfbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('project', 'phase')},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['submission', 'resolved'], name='projects_fe_submiss_d0ac24_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['given_by'], name='projects_fe_given_b_fd4b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['resolved'], name='projects_fe_resolve_fd0542_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['project', 'role'], name='projects_te_project_148273_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='projects_te_user_id_c1145b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('user', 'project')},
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['submission', 'version_number'], name='projects_ve_submiss_ca8ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['uploaded_by'], name='projects_ve_uploade_90a048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('submission', 'version_number')},
        ),
    ]
