# Generated by Django 6.0.4 on 2026-04-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='version',
            field=models.ForeignKey(blank=True, help_text='The specific version this feedback refers to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='projects.version'),
        ),
    ]
