# Generated by Django 6.0.4 on 2026-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('GUIDE', 'Guide/Teacher'), ('COORDINATOR', 'Coordinator'), ('STUDENT', 'Student')], default='STUDENT', help_text='User role determines system access and permissions', max_length=12),
        ),
    ]
